import { Main } from '../Components/Main';
import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'
import { useState,ChangeEvent,useEffect } from "react";
import { useAppDispatch,  useAppSelector} from "../hook";
import {setTerm,setOptions, setSelectedOptions, fetchGeolocation} from '../features/geolocationSlice'
import {fetchWeatherForcast} from '../features/weatherSlice'

// import env from 'react-dotenv';


export default function Home():JSX.Element {
const dispatch = useAppDispatch()
  const {term,options,selectedOption} = useAppSelector(state=> state.geolocation)

  

  const handleOnchange = (e:ChangeEvent<HTMLInputElement>): void => {
    dispatch(setTerm(e.target.value))
    dispatch(fetchGeolocation(e.target.value))
  }

  const fetchWeather = (lon:number, lat:number, name:string) => {
    dispatch(setSelectedOptions([lon, lat]))
    dispatch(setTerm(name))
    dispatch(setOptions([]))
    
  }
  const search = () => {
    if (selectedOption.length > 0) {
      dispatch(fetchWeatherForcast(selectedOption as [number, number]))
    }
    setOptions([])
  }
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
    <Main   term={term} handleOnchange={handleOnchange} options={options}  fetchWeather={fetchWeather} search={search}  />
    </>
  )
}
